spring:
  profiles:
    active: dev
  application:
    name: hris-bank-adapter

xml:
  base:
    commercial:
      endpoint: "http://localhost:8084/ws"
    file:
      path: "C:\\P-DEV\\GitHub\\Server\\HRIS\\xml"



