//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.04.15 at 08:18:22 AM IST 
//


package hris_bank_adapter.wsdl;

import jakarta.xml.bind.annotation.*;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Header"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CompanyRegName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="CompanyRegNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="EmployeeInfo" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="EpfNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="NIC" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="BankInfo"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="BankName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="BankAccount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="BankCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="BranchCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="Salary" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="Footer"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CtrlSum" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "header",
        "employeeInfos",
        "footer"
})
@XmlRootElement(name = "DocumentRequest")
@Getter
@Setter
public class DocumentRequest {

    @XmlElement(name = "Header", required = true)
    protected Header header;
    @XmlElement(name = "EmployeeInfo")
    protected List<EmployeeInfo> employeeInfos;
    @XmlElement(name = "Footer", required = true)
    protected Footer footer;

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="EpfNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="NIC" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="BankInfo"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="BankName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="BankAccount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="BankCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="BranchCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="Salary" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "epfNo",
            "firstName",
            "middleName",
            "lastName",
            "nic",
            "bankInfo"
    })
    @Getter
    @Setter
    public static class EmployeeInfo {

        @XmlElement(name = "EpfNo", required = true)
        protected String epfNo;
        @XmlElement(name = "FirstName", required = true)
        protected String firstName;
        @XmlElement(name = "MiddleName", required = true)
        protected String middleName;
        @XmlElement(name = "LastName", required = true)
        protected String lastName;
        @XmlElement(name = "NIC", required = true)
        protected String nic;
        @XmlElement(name = "BankInfo", required = true)
        protected BankInfo bankInfo;

        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="BankName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="BankAccount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="BankCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="BranchCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="Salary" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "bankName",
                "bankAccount",
                "bankCode",
                "branchCode",
                "salary",
                "currency",
                "description"
        })
        @Getter
        @Setter
        public static class BankInfo {

            @XmlElement(name = "BankName", required = true)
            protected String bankName;
            @XmlElement(name = "BankAccount", required = true)
            protected String bankAccount;
            @XmlElement(name = "BankCode", required = true)
            protected String bankCode;
            @XmlElement(name = "BranchCode", required = true)
            protected String branchCode;
            @XmlElement(name = "Salary")
            protected double salary;
            @XmlElement(name = "Currency")
            protected String currency;
            @XmlElement(name = "Description")
            protected String description;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="CtrlSum" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "ctrlSum"
    })
    @Getter
    @Setter
    public static class Footer {

        @XmlElement(name = "CtrlSum")
        protected BigDecimal ctrlSum;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="CompanyRegName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="CompanyRegNo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "companyRegName",
            "companyRegNo"
    })
    @Getter
    @Setter
    public static class Header {

        @XmlElement(name = "CompanyRegName", required = true)
        protected String companyRegName;
        @XmlElement(name = "CompanyRegNo", required = true)
        protected String companyRegNo;
    }
}
