////
//// This file was generated by the Eclipse Implementation of JAXB, v3.0.2
//// See https://eclipse-ee4j.github.io/jaxb-ri
//// Any modifications to this file will be lost upon recompilation of the source schema.
//// Generated on: 2025.04.15 at 08:18:22 AM IST
////
//
//
//package hris_bank_adapter.wsdl;
//
//import jakarta.xml.bind.annotation.XmlRegistry;
//
//
///**
// * This object contains factory methods for each
// * Java content interface and Java element interface
// * generated in the com.commercialbankportal.banktransfer package.
// * <p>An ObjectFactory allows you to programatically
// * construct new instances of the Java representation
// * for XML content. The Java representation of XML
// * content can consist of schema derived interfaces
// * and classes representing the binding of schema
// * type definitions, element declarations and model
// * groups.  Factory methods for each of these are
// * provided in this class.
// *
// */
//@XmlRegistry
//public class ObjectFactory {
//
//
//    /**
//     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.commercialbankportal.banktransfer
//     *
//     */
//    public ObjectFactory() {
//    }
//
//    /**
//     * Create an instance of {@link DocumentRequest }
//     *
//     */
//    public DocumentRequest createDocumentRequest() {
//        return new DocumentRequest();
//    }
//
//    /**
//     * Create an instance of {@link DocumentRequest.EmployeeInfo }
//     *
//     */
//    public DocumentRequest.EmployeeInfo createDocumentRequestEmployeeInfo() {
//        return new DocumentRequest.EmployeeInfo();
//    }
//
//    /**
//     * Create an instance of {@link DocumentRequest.Header }
//     *
//     */
//    public DocumentRequest.Header createDocumentRequestHeader() {
//        return new DocumentRequest.Header();
//    }
//
//    /**
//     * Create an instance of {@link DocumentRequest.Footer }
//     *
//     */
//    public DocumentRequest.Footer createDocumentRequestFooter() {
//        return new DocumentRequest.Footer();
//    }
//
//    /**
//     * Create an instance of {@link DocumentRequest.EmployeeInfo.BankInfo }
//     *
//     */
//    public DocumentRequest.EmployeeInfo.BankInfo createDocumentRequestEmployeeInfoBankInfo() {
//        return new DocumentRequest.EmployeeInfo.BankInfo();
//    }
//
//
//}
